UPDATE activity
SET
address = data.addr,
city = data.city,
country = data.country
FROM (
SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS row_num
FROM activity
) AS activity_row_num
JOIN (
	VALUES
		(1,'123 Main St', 'New York', 'USA'),
(2, '24 Oak St', 'London', 'UK'),
(3, '56 Pine Ave', 'Paris', 'France'),
(4, '78 Maple St', 'Berlin', 'Germany'),
(5, '90 Elm St', 'Tokyo', 'Japan'),
(6, '12 Cedar St', 'Sydney', 'Australia'),
(7, '34 Birch St', 'Beijing', 'China'),
(8, '45 Fir St', 'Mumbai', 'India'),
(9, '67 Spruce St', 'Moscow', 'Russia'),
(10, '89 Hazel St', 'Sao Paulo', 'Brazil'),
(11, '23 Willow St', 'Mexico City', 'Mexico'),
(12, '98 Olive St', 'Istanbul', 'Turkey'),
(13, '43 Poplar St', 'Kolkata', 'India'),
(14, '75 Cypress St', 'Dhaka', 'Bangladesh'),
(15, '31 Magnolia St', 'Lagos', 'Nigeria'),
(16, '19 Juniper St', 'Buenos Aires', 'Argentina'),
(17, '85 Aspen St', 'Cape Town', 'South Africa'),
(18, '42 Sycamore St', 'Rio de Janeiro', 'Brazil'),
(19, '61 Larch St', 'Karachi', 'Pakistan'),
(20, '29 Eucalyptus St', 'Chennai', 'India'),
(21, '38 Redwood St', 'Lahore', 'Pakistan'),
(22, '94 Walnut St', 'Bangkok', 'Thailand'),
(23, '11 Mulberry St', 'Tehran', 'Iran'),
(24, '58 Tamarack St', 'Dubai', 'UAE'),
(25, '25 Orange St', 'Shanghai', 'China'),
(26, '82 Pecan St', 'Manila', 'Philippines'),
(27, '48 Cedar St', 'Kuala Lumpur', 'Malaysia'),
(28, '65 Maple St', 'Jakarta', 'Indonesia'),
(29, '36 Oak St', 'Ho Chi Minh City', 'Vietnam'),
(30, '97 Birch St', 'Hanoi', 'Vietnam'),
(31, '13 Elm St', 'Singapore', 'Singapore'),
(32, '59 Ash St', 'Hong Kong', 'Hong Kong'),
(33, '71 Beech St', 'Seoul', 'South Korea'),
(34, '44 Spruce St', 'Taipei', 'Taiwan'),
(35, '83 Fir St', 'Busan', 'South Korea'),
(36, '27 Pine St', 'Daegu', 'South Korea'),
(37, '91 Cypress St', 'Daejeon', 'South Korea'),
(38, '63 Walnut St', 'Gwangju', 'South Korea'),
(39, '35 Sycamore St', 'Ulsan', 'South Korea'),
(40, '55 Larch St', 'Pune', 'India'),
(41, '87 Aspen St', 'Surat', 'India'),
(42, '22 Juniper St', 'Kanpur', 'India'),
(43, '76 Magnolia St', 'Nagpur', 'India'),
(44, '39 Redwood St', 'Lucknow', 'India'),
(45, '93 Hickory St', 'Visakhapatnam', 'India'),
(46, '57 Oak St', 'Mysore', 'India'),
(47, '81 Pine Ave', 'Thiruvananthapuram', 'India'),
(48, '33 Maple St', 'Kochi', 'India'),
(49, '95 Fir St', 'Coimbatore', 'India'),
(50, '69 Spruce St', 'Madurai', 'India'),
(51, '41 Cedar St', 'Guangzhou', 'China'),
(52, '89 Hazel St', 'Shenzhen', 'China'),
(53, '17 Elm St', 'Chengdu', 'China'),
(54, '73 Walnut St', 'Tianjin', 'China'),
(55, '29 Larch St', 'Xi an', 'China'),
(56, '99 Sycamore St', 'Wuhan', 'China'),
(57, '53 Ash St', 'Hangzhou', 'China'),
(58, '85 Orange St', 'Suzhou', 'China'),
(59, '37 Birch St', 'Shenyang', 'China'),
(60, '79 Juniper St', 'Dalian', 'China'),
(61, '43 Poplar St', 'Nanjing', 'China'),
(62, '15 Mulberry St', 'Qingdao', 'China'),
(63, '67 Cypress St', 'Zhengzhou', 'China'),
(64, '31 Eucalyptus St', 'Chongqing', 'China'),
(65, '59 Tamarack St', 'Kunming', 'China'),
(66, '23 Pecan St', 'Foshan', 'China'),
(67, '87 Beech St', 'Guiyang', 'China'),
(68, '49 Cedar St', 'Nanning', 'China'),
(69, '13 Olive St', 'Haikou', 'China'),
(70, '75 Larch St', 'Jinan', 'China'),
(71, '35 Maple St', 'Taiyuan', 'China'),
(72, '97 Spruce St', 'Hefei', 'China'),
(73, '55 Pine Ave', 'Changsha', 'China'),
(74, '25 Oak St', 'Xiamen', 'China'),
(75, '83 Walnut St', 'Fuzhou', 'China'),
(76, '47 Hickory St', 'Wenzhou', 'China'),
(77, '19 Juniper St', 'Ningbo', 'China'),
(78, '61 Cypress St', 'Zhuhai', 'China'),
(79, '29 Redwood St', 'Shantou', 'China'),
(80, '93 Sycamore St', 'Quanzhou', 'China'),
(81, '57 Fir St', 'Zhanjiang', 'China'),
(82, '81 Larch St', 'Huizhou', 'China'),
(83, '33 Orange St', 'Dongguan', 'China'),
(84, '95 Tamarack St', 'Shaoxing', 'China'),
(85, '69 Eucalyptus St', 'Jining', 'China'),
(86, '41 Pecan St', 'Weifang', 'China'),
(87, '89 Mulberry St', 'Linyi', 'China'),
(88, '17 Ash St', 'Dezhou', 'China'),
(90, '29 Cedar St', 'Binzhou', 'China'),
(91, '99 Walnut St', 'Heze', 'China'),
(92, '53 Spruce St', 'Jiangmen', 'China'),
(93, '85 Cypress St', 'Zhongshan', 'China'),
(94, '37 Oak St', 'Mianyang', 'China'),
(95, '79 Hickory St', 'Luzhou', 'China'),
(96, '43 Pine Ave', 'Xining', 'China'),
(97, '15 Maple St', 'Yinchuan', 'China'),
(98, '67 Larch St', 'Hohhot', 'China'),
(99, '31 Fir St', 'Lhasa', 'China'),
(100, '59 Sycamore St', 'Urumqi', 'China')
) AS data (row_num, addr, city, country) ON activity_row_num.row_num = data.row_num
WHERE activity.id = activity_row_num.id;